version: '3.6'
services:
  api:
    image: sample-hapi-app
    build: 
      context: .
      dockerfile: ./modules/api/Dockerfile
    # networks:
    #   - backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app

#   web-cli:
#     image: sample-hapi-app
#     networks:
#       - backend
#     command: sh

# networks:
#   backend:
#     driver: bridge

# volumes:
#   yarn-cache:
#     driver: 'local'
